### ISSUE TITLE
Broken link to forum on README

### ISSUE THREAD

**Issue by nicomgd** [KhronosGroup/KTX#11]
The following link is broken

https://www.khronos.org/message_boards/forumdisplay.php/103-KTX-file-format-for-OpenGL-OpenGL-ES-and-WebGL-textures

Cut&paste from the repo README

**Comment by msc-** [comment]
Fixed in both branches. Thanks for the report.

**Comment by nicomgd** [comment]
Hey thanks for your quick reply, it seems though that the fix only landed in 'incoming' branch, the 'master' link is still broken for me.

**Comment by msc-** [comment]
Oops! Sorry about that. I only pushed 'incoming'. I've pushed 'master' now.
